[project]
name = "fast-eip1559-set"
authors = ["Stacks Developer"]
description = "Block-height-based dynamic event feedback mechanism"
telemetry = false
requirements = []
[contracts.eip1559-feedback-set]
path = "contracts/eip1559-feedback-set.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
